name: first-action
on: push
jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      - name: Get the code
        uses: actions/checkout@v4
      - name: installs bun
        run: |
          sudo apt-get update
          curl -fsSL https://bun.sh/install | bash
      - name: Test the project
        run: |
          bun run test
      - name: Run the project
        run: |
          bun run start
